workers_dev = true
name = "my-react-router-app"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "react-router-db"
database_id = "0acf3f3b-4055-4f51-92f8-df73b3e67d29"
migrations_dir = "drizzle"


